# Model Eğitimi için Verileri Düzenliyorum

## Kütüphaneler

In [ ]:
%pip install -U pandas
%pip install -U scikit-learn

## Verileri Okuma

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
df = pd.read_csv(r"data\heart.csv")
df.head(10)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0

In [3]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

 ## Verilerin Sayısal Değerlere Dönüştürülmesi 
 - Verilerin sayısal değerlere dönüştürülmesi işlemi (Categorical Encoding) yapılıyor

In [4]:
categorical_encoding = ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"]

for column in categorical_encoding:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    
    print(f"--- {column} ---")
    for label, value in zip(le.classes_, range(len(le.classes_))):
        print(f"'{label}' : {value}")
    print("-" * 15)

df.head(10)

--- Sex ---
'F' : 0
'M' : 1
---------------
--- ChestPainType ---
'ASY' : 0
'ATA' : 1
'NAP' : 2
'TA' : 3
---------------
--- RestingECG ---
'LVH' : 0
'Normal' : 1
'ST' : 2
---------------
--- ExerciseAngina ---
'N' : 0
'Y' : 1
---------------
--- ST_Slope ---
'Down' : 0
'Flat' : 1
'Up' : 2
---------------

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0
5,39,1,2,120,339,0,1,170,0,0.0,2,0
6,45,0,1,130,237,0,1,170,0,0.0,2,0
7,54,1,1,110,208,0,1,142,0,0.0,2,0
8,37,1,0,140,207,0,1,130,1,1.5,1,1
9,48,0,1,120,284,0,1,120,0,0.0,2,0

## Verilere Standardizasyon İşlemi

- Model büyük sayılı verilerin kalp krizi riski için daha önemli olduğunu sanabilir  
- Sayısal verileri ortalaması 0, standart sapması 1 olacak şekilde güncelliyoruz

In [5]:
numeric_columns = ["Age","RestingBP","Cholesterol","MaxHR","Oldpeak"]

scaler = StandardScaler()
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])
df.head(10)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,-1.433140,1,1,0.410909,0.825070,0,1,1.382928,0,-0.832432,2,0
1,-0.478484,0,2,1.491752,-0.171961,0,1,0.754157,0,0.105664,1,1
2,-1.751359,1,1,-0.129513,0.770188,0,2,-1.525138,0,-0.832432,2,0
3,-0.584556,0,0,0.302825,0.139040,0,1,-1.132156,1,0.574711,1,1
4,0.051881,1,2,0.951331,-0.034755,0,1,-0.581981,0,-0.832432,2,0
5,-1.539213,1,2,-0.669935,1.282424,0,1,1.304332,0,-0.832432,2,0
6,-0.902775,0,1,-0.129513,0.349422,0,1,1.304332,0,-0.832432,2,0
7,0.051881,1,1,-1.210356,0.084157,0,1,0.203982,0,-0.832432,2,0
8,-1.751359,1,0,0.410909,0.075010,0,1,-0.267596,1,0.574711,1,1
9,-0.584556,0,1,-0.669935,0.779335,0,1,-0.660578,0,-0.832432,2,0

## Model Eğitimi için Hazırlanmış Verilerin Çıktısını Alıyorum

In [6]:
df.to_csv(r"data\heart_processed.csv", index= False)