# Model 1 (Yapay Sinir Ağları)

In [ ]:
%pip install imblearn
%pip install tensorflow

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE
from tensorflow.keras.models import Sequential  # type: ignore
from tensorflow.keras.layers import Dense  # type: ignore
from tensorflow.keras.optimizers import Adam  # type: ignore

df = pd.read_csv(r'data\heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
# Kategorik verileri sayısal değerlere dönüştürelim
label_encoder = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_cp = LabelEncoder()
df['Sex'] = label_encoder_sex.fit_transform(df['Sex'])
df['ChestPainType'] = label_encoder_cp.fit_transform(df['ChestPainType'])
df['RestingECG'] = label_encoder.fit_transform(df['RestingECG'])
df['ExerciseAngina'] = label_encoder.fit_transform(df['ExerciseAngina'])
df['ST_Slope'] = label_encoder.fit_transform(df['ST_Slope'])
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [4]:
#Girdi ve Çıktıyı belirle
X = df.drop('HeartDisease' , axis=1)
y = df['HeartDisease']

#veriyi eğitim ve test olarak ayıralım
X_train, X_test , y_train, y_test = train_test_split(X,y, test_size=0.3 , random_state=42)

#veri dengesizliğini düzelt
# SMOTE (Synthetic Minority Over-sampling Technique) (Sentetik Azınlık Aşırı Örnekleme Tekniği)
smote = SMOTE(random_state=42)
X_train_smote , y_train_smote = smote.fit_resample(X_train, y_train)

#veriyi ölçeklendir
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_smote)
X_test_scaled = scaler.transform(X_test)

In [ ]:

# Model 1 (Yapay Sinir Ağları)
model = Sequential()
model.add(Dense(16, input_dim=X_train_scaled.shape[1] ,activation = 'relu'))
model.add(Dense(1, activation='sigmoid'))
#modeli derleyelim
optimizer = Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy' , optimizer = optimizer , metrics=['accuracy'])
#modeli eğitielim
model.fit(X_train_scaled, y_train_smote, epochs=100 , verbose=1 , validation_data=(X_test_scaled, y_test) )
loss, accuracy = model.evaluate(X_test_scaled, y_test)

Model 1: Yapay Sinir Ağları
WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\amate\Desktop\Uni\Projeler\kalp-krizi-risk-tahmini\.env\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.5654 - loss: 0.8218 - val_accuracy: 0.5290 - val_loss: 0.8262
Epoch 2/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6308 - loss: 0.7068 - val_accuracy: 0.5942 - val_loss: 0.7146
Epoch 3/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6919 - loss: 0.6230 - val_accuracy: 0.6522 - val_loss: 0.6267
Epoch 4/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7224 - loss: 0.5600 - val_accuracy: 0.6920 - val_loss: 0.5661
Epoch 5/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7587 - loss: 0.5164 - val_accuracy: 0.7464 - val_loss: 0.5204
Epoch 6/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7849 - loss: 0.4841 - val_accuracy: 0.7862 - val_loss: 0.4865
Epoch 7/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7878 - loss: 0.4615 - val_accuracy: 0.7971 - val_loss: 0.4606
Epoch 8/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7994 - loss: 0.4439 - val_accuracy: 0.8188 - val_loss: 0.4407
Epoch 9/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8110 - loss: 0.4303 - val_accuracy: 0.8297 - val_loss: 0.4266
Epoch 10/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8241 - loss: 0.4195 - val_accuracy: 0.8297 - val_loss: 0.4141
Epoch 11/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8314 - loss: 0.4110 - val_accuracy: 0.8406 - val_loss: 0.4057
Epoch 12/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8372 - loss: 0.4045 - val_accuracy: 0.8442 - val_loss: 0.3963
Epoch 13/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8416 - loss: 0.3983 - val_accuracy: 0.8478 - val_loss: 0.3914
Epoch 14/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8416 - loss: 0.3937 - val_accuracy: 0.8478 - val_loss: 0.3872
Epoch 15/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8445 - loss: 0.3891 - val_accuracy: 0.8478 - val_loss: 0.3833
Epoch 16/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8488 - loss: 0.3851 - val_accuracy: 0.8478 - val_loss: 0.3774
Epoch 17/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8532 - loss: 0.3814 - val_accuracy: 0.8551 - val_loss: 0.3750
Epoch 18/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8517 - loss: 0.3782 - val_accuracy: 0.8514 - val_loss: 0.3718
Epoch 19/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8561 - loss: 0.3757 - val_accuracy: 0.8514 - val_loss: 0.3697
Epoch 20/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8561 - loss: 0.3725 - val_accuracy: 0.8514 - val_loss: 0.3662
Epoch 21/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8547 - loss: 0.3701 - val_accuracy: 0.8514 - val_loss: 0.3645
Epoch 22/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8547 - loss: 0.3676 - val_accuracy: 0.8514 - val_loss: 0.3631
Epoch 23/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8561 - loss: 0.3655 - val_accuracy: 0.8514 - val_loss: 0.3612
Epoch 24/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8576 - loss: 0.3636 - val_accuracy: 0.8514 - val_loss: 0.3601
Epoch 25/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8576 - loss: 0.3616 - val_accuracy: 0.8514 - val_loss: 0.3587
Epoch 26/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8590 - loss: 0.3600 - val_accuracy: 0.8551 - val_loss: 0.3566
Epoch 27/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8561 - loss: 0.3582 - val_accuracy: 0.8551 - val_loss: 0.3551
Epoch 28/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8547 - loss: 0.3566 - val_accuracy: 0.8551 - val_loss: 0.3545
Epoch 29/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8532 - loss: 0.3550 - val_accuracy: 0.8551 - val_loss: 0.3529
Epoch 30/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8561 - loss: 0.3536 - val_accuracy: 0.8551 - val_loss: 0.3515
Epoch 31/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8532 - loss: 0.3522 - val_accuracy: 0.8514 - val_loss: 0.3507
Epoch 32/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8547 - loss: 0.3508 - val_accuracy: 0.8514 - val_loss: 0.3488
Epoch 33/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8590 - loss: 0.3495 - val_accuracy: 0.8514 - val_loss: 0.3465
Epoch 34/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8590 - loss: 0.3486 - val_accuracy: 0.8514 - val_loss: 0.3476
Epoch 35/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8605 - loss: 0.3465 - val_accuracy: 0.8514 - val_loss: 0.3449
Epoch 36/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8605 - loss: 0.3456 - val_accuracy: 0.8514 - val_loss: 0.3444
Epoch 37/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8619 - loss: 0.3442 - val_accuracy: 0.8514 - val_loss: 0.3432
Epoch 38/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8634 - loss: 0.3428 - val_accuracy: 0.8514 - val_loss: 0.3421
Epoch 39/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8619 - loss: 0.3419 - val_accuracy: 0.8551 - val_loss: 0.3406
Epoch 40/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8619 - loss: 0.3402 - val_accuracy: 0.8659 - val_loss: 0.3402
Epoch 41/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8619 - loss: 0.3391 - val_accuracy: 0.8623 - val_loss: 0.3374
Epoch 42/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8619 - loss: 0.3380 - val_accuracy: 0.8659 - val_loss: 0.3384
Epoch 43/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8634 - loss: 0.3368 - val_accuracy: 0.8623 - val_loss: 0.3375
Epoch 44/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8648 - loss: 0.3356 - val_accuracy: 0.8623 - val_loss: 0.3361
Epoch 45/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8648 - loss: 0.3346 - val_accuracy: 0.8587 - val_loss: 0.3359
Epoch 46/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8634 - loss: 0.3338 - val_accuracy: 0.8587 - val_loss: 0.3373
Epoch 47/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8634 - loss: 0.3326 - val_accuracy: 0.8587 - val_loss: 0.3356
Epoch 48/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8648 - loss: 0.3316 - val_accuracy: 0.8623 - val_loss: 0.3340
Epoch 49/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8663 - loss: 0.3306 - val_accuracy: 0.8587 - val_loss: 0.3333
Epoch 50/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8677 - loss: 0.3296 - val_accuracy: 0.8623 - val_loss: 0.3321
Epoch 51/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8663 - loss: 0.3286 - val_accuracy: 0.8659 - val_loss: 0.3308
Epoch 52/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8663 - loss: 0.3279 - val_accuracy: 0.8659 - val_loss: 0.3319
Epoch 53/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8648 - loss: 0.3269 - val_accuracy: 0.8623 - val_loss: 0.3318
Epoch 54/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8663 - loss: 0.3263 - val_accuracy: 0.8587 - val_loss: 0.3309
Epoch 55/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8677 - loss: 0.3254 - val_accuracy: 0.8623 - val_loss: 0.3310
Epoch 56/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8692 - loss: 0.3246 - val_accuracy: 0.8623 - val_loss: 0.3288
Epoch 57/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8706 - loss: 0.3235 - val_accuracy: 0.8659 - val_loss: 0.3281
Epoch 58/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8692 - loss: 0.3229 - val_accuracy: 0.8659 - val_loss: 0.3282
Epoch 59/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8692 - loss: 0.3219 - val_accuracy: 0.8659 - val_loss: 0.3270
Epoch 60/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8692 - loss: 0.3212 - val_accuracy: 0.8659 - val_loss: 0.3259
Epoch 61/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8692 - loss: 0.3205 - val_accuracy: 0.8659 - val_loss: 0.3258
Epoch 62/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8692 - loss: 0.3195 - val_accuracy: 0.8659 - val_loss: 0.3245
Epoch 63/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8692 - loss: 0.3191 - val_accuracy: 0.8659 - val_loss: 0.3261
Epoch 64/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8706 - loss: 0.3181 - val_accuracy: 0.8659 - val_loss: 0.3239
Epoch 65/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8721 - loss: 0.3176 - val_accuracy: 0.8659 - val_loss: 0.3250
Epoch 66/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8721 - loss: 0.3166 - val_accuracy: 0.8696 - val_loss: 0.3226
Epoch 67/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8721 - loss: 0.3161 - val_accuracy: 0.8659 - val_loss: 0.3222
Epoch 68/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8735 - loss: 0.3154 - val_accuracy: 0.8659 - val_loss: 0.3237
Epoch 69/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8735 - loss: 0.3144 - val_accuracy: 0.8659 - val_loss: 0.3229
Epoch 70/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8735 - loss: 0.3137 - val_accuracy: 0.8659 - val_loss: 0.3233
Epoch 71/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8721 - loss: 0.3133 - val_accuracy: 0.8732 - val_loss: 0.3186
Epoch 72/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8721 - loss: 0.3123 - val_accuracy: 0.8696 - val_loss: 0.3202
Epoch 73/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8735 - loss: 0.3118 - val_accuracy: 0.8696 - val_loss: 0.3214
Epoch 74/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8750 - loss: 0.3112 - val_accuracy: 0.8696 - val_loss: 0.3203
Epoch 75/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8735 - loss: 0.3106 - val_accuracy: 0.8696 - val_loss: 0.3197
Epoch 76/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - loss: 0.3099 - val_accuracy: 0.8696 - val_loss: 0.3174
Epoch 77/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3097 - val_accuracy: 0.8768 - val_loss: 0.3161
Epoch 78/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - loss: 0.3089 - val_accuracy: 0.8732 - val_loss: 0.3196
Epoch 79/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8750 - loss: 0.3080 - val_accuracy: 0.8732 - val_loss: 0.3185
Epoch 80/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8750 - loss: 0.3075 - val_accuracy: 0.8732 - val_loss: 0.3181
Epoch 81/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3069 - val_accuracy: 0.8732 - val_loss: 0.3167
Epoch 82/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8750 - loss: 0.3064 - val_accuracy: 0.8732 - val_loss: 0.3164
Epoch 83/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8779 - loss: 0.3056 - val_accuracy: 0.8732 - val_loss: 0.3166
Epoch 84/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8779 - loss: 0.3057 - val_accuracy: 0.8696 - val_loss: 0.3161
Epoch 85/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8779 - loss: 0.3047 - val_accuracy: 0.8696 - val_loss: 0.3162
Epoch 86/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8779 - loss: 0.3040 - val_accuracy: 0.8696 - val_loss: 0.3169
Epoch 87/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8794 - loss: 0.3035 - val_accuracy: 0.8768 - val_loss: 0.3159
Epoch 88/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8794 - loss: 0.3027 - val_accuracy: 0.8732 - val_loss: 0.3145
Epoch 89/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8794 - loss: 0.3025 - val_accuracy: 0.8732 - val_loss: 0.3153
Epoch 90/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8794 - loss: 0.3015 - val_accuracy: 0.8732 - val_loss: 0.3144
Epoch 91/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8794 - loss: 0.3011 - val_accuracy: 0.8732 - val_loss: 0.3124
Epoch 92/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8808 - loss: 0.3005 - val_accuracy: 0.8768 - val_loss: 0.3134
Epoch 93/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8794 - loss: 0.2998 - val_accuracy: 0.8768 - val_loss: 0.3127
Epoch 94/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8779 - loss: 0.2994 - val_accuracy: 0.8768 - val_loss: 0.3136
Epoch 95/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8779 - loss: 0.2988 - val_accuracy: 0.8768 - val_loss: 0.3132
Epoch 96/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8779 - loss: 0.2980 - val_accuracy: 0.8768 - val_loss: 0.3127
Epoch 97/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8794 - loss: 0.2980 - val_accuracy: 0.8768 - val_loss: 0.3138
Epoch 98/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8794 - loss: 0.2974 - val_accuracy: 0.8768 - val_loss: 0.3142
Epoch 99/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8794 - loss: 0.2967 - val_accuracy: 0.8804 - val_loss: 0.3124
Epoch 100/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8794 - loss: 0.2960 - val_accuracy: 0.8768 - val_loss: 0.3128
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8768 - loss: 0.3128

# Model 2 (Random Forest)

In [ ]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_smote, y_train_smote)
y_pred_rf = rf_model.predict(X_test_scaled)
rf_accuracy = accuracy_score(y_test, y_pred_rf)

# Model 3 (Decision Tree) (Karar Ağaçları)

In [ ]:
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_smote , y_train_smote)
y_pred_dt = dt_model.predict(X_test_scaled)
dt_accuracy = accuracy_score(y_test , y_pred_dt)

# Model 4 (Logistic Regression) (Lojistik Regresyon)

In [ ]:
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train_smote , y_train_smote)
y_pred_lr = lr_model.predict(X_test_scaled)
lr_accuracy = accuracy_score(y_test, y_pred_lr)

# Sonuçlar

In [9]:
print(f'Yapay Sinir Ağı Doğruluk Oranı : {accuracy * 100:.2f}%')
print(f'Random Forest Doğruluk Oranı : {rf_accuracy * 100:.2f}%')
print(f'Karar Ağaçları Doğruluk Oranı : {dt_accuracy * 100:.2f}%')
print(f'Lojistik Doğruluk Oranı : {lr_accuracy * 100:.2f}%')

Yapay Sinir Ağı Doğruluk Oranı : 87.68%
Random Forest Doğruluk Oranı : 70.65%
Karar Ağaçları Doğruluk Oranı : 31.16%
Lojistik Doğruluk Oranı : 85.51%

# Kullanıcıdan Alınan Veri ile Modelin Tahmini

In [10]:
while True:
    user_input_1 = float(input('Yaşınızı Giriniz: '))
    user_input_2 = input('Cinsiyetinizi Giriniz (M, F): ')
    user_input_3 = input('Göğüs Ağrısı Tipini Giriniz (ATA, NAP, ASY, TA): ')
    user_input_4 = float(input('Dinlenme Kan Basıncınızı Giriniz: '))
    user_input_5 = float(input('Kolesterol Değerinizi Giriniz: '))

    try:
        # Kullanıcı verilerini sayısal hale getirme
        user_data = pd.DataFrame({
            'Age': [user_input_1],
            'Sex': [label_encoder_sex.transform([user_input_2])[0]],  # Label encoder'ı düzgün kullan
            'ChestPainType': [label_encoder_cp.transform([user_input_3])[0]],  # Aynı şekilde chest pain tipi
            'RestingBP': [user_input_4],
            'Cholesterol': [user_input_5],
            'FastingBS': [0],  # Sabit bir değer
            'RestingECG': [0],  # Sabit bir değer
            'MaxHR': [150],  # Sabit örnek değer
            'ExerciseAngina': [0],  # Sabit bir değer
            'Oldpeak': [0.0],
            'ST_Slope': [1]
        })

        # Veriyi ölçeklendirme
        user_data_scaled = scaler.transform(user_data)

        # Tahmin yapma
        prediction = model.predict(user_data_scaled)
        print(f'Tahmin sonucu: Kalp hastalığı risk oranınız: {prediction[0][0]:.4f}')

    except ValueError as e:
        print(f"Bir hata oluştu: {e}. Lütfen girdiğiniz bilgileri kontrol edin.")

    # Yeni tahmin almak için devam edelim
    devam = input('Başka bir tahmin yapmak istiyor musunuz? (E/H): ')
    if devam.lower() != 'e':
        break

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step
Tahmin sonucu: Kalp hastalığı risk oranınız: 0.4338